CREATE DATABASE IF NOT EXISTS LOVINYL;
USE LOVINYL;

CREATE TABLE IF NOT EXISTS TAB_USER(
ID_CADASTRO INT PRIMARY KEY AUTO_INCREMENT,
NOME_USER VARCHAR(45) NOT NULL,
CELULAR_USER CHAR(11) NOT NULL,
CPF_USER CHAR(11) NOT NULL,
EMAIL_USER VARCHAR(50) NOT NULL,
SENHA_USER VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAB_DISCO(
ID_DISCO INT PRIMARY KEY AUTO_INCREMENT,
NOME_DISCO VARCHAR (50),
GENERO VARCHAR (50),
LANCAMENTO VARCHAR(50)
) AUTO_INCREMENT = 100;

CREATE TABLE IF NOT EXISTS TAB_MUSICA(
ID_MUSICA INT PRIMARY KEY AUTO_INCREMENT,
NOME_MUSICA VARCHAR(50),
NOME_ARTISTA VARCHAR (50),
FK_DISCO INT,
FOREIGN KEY (FK_DISCO) REFERENCES TAB_DISCO(ID_DISCO)
) AUTO_INCREMENT = 500;

CREATE TABLE IF NOT EXISTS TAB_HISTORICO(
ID_HISTORICO INT PRIMARY KEY AUTO_INCREMENT,
FK_DISCO INT,
FOREIGN KEY (FK_DISCO) REFERENCES TAB_DISCO(ID_DISCO),
FK_USER INT,
FOREIGN KEY (FK_USER) REFERENCES TAB_USER(ID_CADASTRO),
DATA_REPRODUCAO DATETIME,
CONTAGEM INT
) AUTO_INCREMENT = 1000;

CREATE TABLE IF NOT EXISTS TAB_AVISO (
	ID_AVISO INT PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(100),
    DESCRICAO VARCHAR(150),
	FK_USER INT,
	FOREIGN KEY (FK_USER) REFERENCES TAB_USER(ID_CADASTRO)
) AUTO_INCREMENT = 2000; 

SELECT * FROM TAB_USER;
SELECT * FROM TAB_MUSICA;
SELECT * FROM TAB_DISCO;
SELECT * FROM TAB_HISTORICO;
SELECT * FROM TAB_AVISO;

-- DROP DATABASE LOVINYL;	

