CREATE DATABASE IF NOT EXISTS LOVINYL;
USE LOVINYL;

CREATE TABLE IF NOT EXISTS TAB_USER(
ID_CADASTRO INT PRIMARY KEY AUTO_INCREMENT,
NOME_USER VARCHAR(45) NOT NULL,
CELULAR_USER CHAR(11) NOT NULL,
CPF_USER CHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAB_GENERO(
ID_GENERO INT PRIMARY KEY AUTO_INCREMENT,
NOME_GENERO VARCHAR (45) NOT NULL,
INFO_GENERO VARCHAR(300)
) AUTO_INCREMENT = 1000;

CREATE TABLE IF NOT EXISTS TAB_MUSICA(
ID_MUSICA INT PRIMARY KEY AUTO_INCREMENT,
NOME_MUSICA VARCHAR(45) NOT NULL,
NOME_ARTISTA VARCHAR(45) NOT NULL,
INFO_DISCO VARCHAR(300),
FK_GENERO INT,
FOREIGN KEY (FK_GENERO) REFERENCES TAB_GENERO(ID_GENERO)
) AUTO_INCREMENT = 10000;

CREATE TABLE IF NOT EXISTS TAB_HISTORICO(
FK_MUSICA INT,
FOREIGN KEY (FK_MUSICA) REFERENCES TAB_MUSICA(ID_MUSICA),
FK_USER INT,
FOREIGN KEY (FK_USER) REFERENCES TAB_USER(ID_CADASTRO),
DATA_REPRODUCAO DATETIME
);